// Auth
export const LOGIN_IN_PROGRESS = "LOGIN_IN_PROGRESS";
export const LOGIN_COMPLETED = "LOGIN_COMPLETED";
export const LOGIN_FAILD = "LOGIN_FAILD";
export const LOGOUT = "LOGOUT";


export const GET_OTHER_USER_IN_PROGRESS = "GET_OTHER_USER_IN_PROGRESS";
export const GET_OTHER_USER_COMPLETED = "GET_OTHER_USER_COMPLETED";
export const SET_OTHER_USER_DATA = " SET_OTHER_USER_DATA";

export const GET_USER_INFO_IN_PROGRESS = "GET_USER_INFO_IN_PROGRESS";
export const GET_USER_INFO_COMPLETED = "GET_USER_INFO_COMPLETED";

export const PATCH_USER_INFO_IN_PROGRESS = "PATCH_USER_INFO";

export const SET_USER_AUTHENTICATION = "SET_USER_AUTHENTICATION";
export const SET_USER_INFO = "SET_USER_INFO";

export const POST_NEW_USER_PROFILE_IN_PROGRESS =
  "POST_NEW_USER_PROFILE_IN_PROGRESS";
export const POST_NEW_USER_PROFILE_COMPLETED =
  "POST_NEW_USER_PROFILE_COMPLETED";

//Books
export const GET_BOOK_DATA_IN_PROGRESS = "GET_BOOK_DATA_IN_PROGRESS";
export const SET_BOOKS = "SET_BOOKS";

//Feeds
export const GET_FEEDS_IN_PROGRESS = "GET_FEEDS_IN_PROGRESS";
export const SET_FEEDS = "SET_FEEDS";
export const POST_FEEDS_IN_PROGRESS = "POST_FEEDS_IN_PROGRESS";

// Feed comments
export const POST_COMMENT_IN_PROGRESS = "POST_COMMENT_IN_PROGRESS";
export const SET_COMMENT = "SET_COMMENT";

//Trades

// Http Error handling
export const HTTP_404_ERROR = "HTTP_404_ERROR";
export const HTTP_500_ERROR = "HTTP_500_ERROR";
export const HTTP_OTHER_ERROR = "HTTP_OTHER_ERROR";
